# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jjacobi <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/18 00:06:13 by jjacobi           #+#    #+#              #
#    Updated: 2016/08/18 14:55:39 by jjacobi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILES = main.c operators.c treatment.c utilities.c

all:
	gcc -o do-op -Wall -Werror -Wall $(FILES)

clean:
	rm -f do-op
